config/routes.rb
Manyou::Application.routes.draw do

  root :to => 'home#index'

  get   :latest,   :to => 'home#latest',  :as => :latest_home

  match "/uploads/*path" => "gridfs#serve"

  scope :module => :member do

    get     :login,     :to => 'sessions#new',      :as => :new_session
    post    :login,     :to => 'sessions#create',   :as => :session
    get     :logout,    :to => 'sessions#destroy',  :as => :destroy_session

    resource :account

    resources :users, :only => [:index, :new, :create, :tagged] do
      collection do
        get 'tagged/:key', :action => :tagged, :constraints => { :key => /[^\/]+/ }, :as => :tagged
      end
    end

    resources :users, :path => :user, :except => [:index, :new, :create, :tagged] do
      member do
        get :follow
        get :unfollow
      end
    end

    get 'bookmarks/add*path' => 'bookmarks#create',    :as => :create_bookmark
    get 'bookmarks/del*path' => 'bookmarks#destroy',   :as => :destroy_bookmark

  end

  scope :module => :forum do

    resource :search

    resources :nodes, :only => [:index, :new, :create, :tagged] do
      collection do
        get 'tagged/:key',  :action => :tagged, :constraints => { :key => /[^\/]+/ },   :as => :tagged
      end
    end

    resources :nodes, :path => :node, :except => [:index, :new, :create, :tagged] do
    end

    resources :topics, :only => [:index, :new, :create, :tagged] do
      collection do
        get 'tagged/:key',  :action => :tagged, :constraints => { :key => /[^\/]+/ },   :as => :tagged
      end
    end
    resources :topics, :path => :topic, :except => [:index, :new, :create, :tagged] do
      member do
        get :voteup
        get :votedown
        get :follow
        get :unfollow
      end

      resources :replies do
        member do
          get :voteup
          get :votedown
        end
      end
    end

  end

  namespace :dashboard do
    root :to => 'home#index'

    resources :users, :topics, :tags, :settings
  end

  match '*path', :to => 'errors#routing'

end

app/models/topic.rb
class Topic
  include Mongoid::Document
  include Mongoid::Timestamps
  include Manyou::DB::Vote
  include Manyou::DB::AutoIncrement

  include ActionView::Helpers::SanitizeHelper
  include ActionView::Helpers::TextHelper

  ai_field :short_id

  field :thumbnail
  #mount_uploader :thumbnail, TopicThumbnailUploader

  field :title,                 :type => String
  field :content,               :type => String
  field :status,                :type => String,    :default => 'normal'
  field :tag,                   :type => String
  #field :type,                  :type => Array,     :default => []

  STATUS    = ['normal', 'ban']
  #TYPE      = ['tweet', 'article', 'media']

  attr_accessible :title, :content, :tag


  field :bookmarks,             :type => Integer,   :default => 0
  field :hits,                  :type => Integer,   :default => 0

  field :edited_at,             :type => Time,      :default => Time.now
  field :replied_at,            :type => Time,      :default => Time.now

  belongs_to :author,           :class_name => 'User', :inverse_of => 'topics'

  embeds_many :replies,         :class_name => 'TopicReply'

  # 多媒体内容 暂时搁置 放到以后再处理吧
  #embeds_many :media,           :class_name => 'TopicMedium'
  #field :media_type,            :type => Array,     :default => []

  has_and_belongs_to_many :followers,   :class_name => 'User'
  has_and_belongs_to_many :nodes,       :class_name => 'Node'

  #has_and_belongs_to_many :meta_tags, :class_name => 'Tag'


  scope :find_by_author,    ->(id)  { where(:author_id => id) }
  scope :find_by_nodes,      ->(nodes){ where(:node_ids.in => nodes ) }

  validates_presence_of     :content
  validates_presence_of     :author
  validates_presence_of     :tag

  #validates_inclusion_of    :type,      :in => TYPE, :allow_blank => true
  validates_inclusion_of    :status,    :in => STATUS, :allow_blank => true

  before_save do
    nodes.concat Node.find_or_create_nodes(tag) if !tag.blank?
  end

  def to_param
    short_id.to_i.to_s
  end

  def format_title(length = 0, omission = '...')
    if read_attribute(:title).blank?
      content = CGI::unescapeHTML(read_attribute(:content))
      content = sanitize(content.bbcode_to_html({}), :tags => %w())
      if length == 0
        content
      else
        truncate(content, :length => length, :omission => omission)
      end
    else
      read_attribute(:title)
    end
  end

  def self.nodes_could
    map = <<EOF
function() {
    var date=new Date();
    date.setDate(date.getDate()-30);

    if (!this.node_ids && this.created_at < date) {
        return;
    }

    for (index in this.node_ids) {
        emit(this.node_ids[index], 1);
    }
}
EOF
    reduce = <<EOF
function(previous, current) {
    var count = 0;

    for (index in current) {
        count += current[index];
    }

    return count;
}
EOF
    collection.mapreduce(map, reduce, {:out => 'nodes_could'}).find({}, :sort => [:value, :desc]).collect{|node| Node.find node['_id'] }.delete_if{|node| node.nil?}
    rescue Mongo::OperationFailure
      []
  end

end

app/controllers/forum/nodes_controller.rb
class Forum::NodesController < ApplicationController

  before_filter :except => [:index, :new, :create] do
    @node = load_node(params[:id])
  end

  def index
  end

=begin
  def tagged
    @keys = Tag.find_tags params[:key].split('+')
    @topics = Topic.where(:tag_ids.in => @nodes.collect{|node| node._id }).and(:tag_ids.all => @keys.collect{|key| key._id }).desc(:replied_at, :created_at).paginate :per_page => 20, :page => params[:page]
    render :show
  end
=end

  def new
    @node = Node.new
  end

  def create
    @node = Node.new params[:node]
    if @node.save
      redirect_to node_path(@node)
    else
      render :new
    end
  end

  def show
    @topics = @node.topics.desc(:replied_at, :created_at).paginate :per_page => 20, :page => params[:page]
  end

  def edit
  end

  def update
    if @node.update_attributes params[:node]
      redirect_to node_path(@node)
    else
      render :edit
    end
  end

end

app/controllers/forum/replies_controller.rb
class Forum::RepliesController < ApplicationController

  before_filter :authenticate_user!

  before_filter do
    load_topic(params[:topic_id] || params[:id])
  end

  before_filter :except => [:create] do
    load_reply params[:id]
  end

  def create
    @reply = @topic.replies.new params[:topic_reply]
    @reply.floor =  @topic.replies.count + 1
    @reply.author = current_user
    if @reply.save
      @topic.replied_at = Time.now
      @topic.save
      flash[:notice] = "reply successfully."
    #else
      #render :new
    end
    redirect_to topic_path(@topic)
  end

  def destroy
    redirect_to topic_path(@topic)
  end

  def voteup
    @reply.vote!(current_user)
    redirect_to topic_path(@topic, :anchor => "reply#{@reply.floor}")
  end

  def votedown
    @reply.vote!(current_user, -1)
    redirect_to topic_path(@topic, :anchor => "reply#{@reply.floor}")
  end
end

app/controllers/forum/topics_controller.rb
class Forum::TopicsController < ApplicationController

  before_filter :authenticate_user!, :except => [:index, :show, :tagged]

  before_filter :except => [:index, :new, :create, :tagged] do
    load_topic(params[:id])
    add_breadcrumb t('breadcrumbs.topics'), topics_path
  end

  def index
    @topics = Topic.desc(:replied_at, :created_at).paginate :per_page => 20, :page => params[:page]
  end

  def tagged
    @keys = Tag.find_tags params[:key].split('+')
    @topics = Topic.where(:tag_ids.all => @keys.collect{|key| key._id }).desc(:replied_at, :created_at).paginate :per_page => 20, :page => params[:page]
  end

  def new
    #authorize! :create, @topic
    @topic = Topic.new
    @topic.type = params[:type] if params[:type] && Topic::TYPE.include?(params[:type])
  end

  def create
    #authorize! :create, @topic
    @topic = Topic.new params[:topic]
    @topic.author = current_user
    if @topic.save
      redirect_to topic_path(@topic)
    else
      render :new
    end
  end

  def show
    add_breadcrumb @topic.format_title(30, '...'), topic_path(@topic)
    @replies = @topic.replies.paginate :per_page => 20, :page => (params[:page] ||= (@topic.replies.count/20).to_i+1)
    recent_read @topic
  end

  def edit
    authorize! :update, @topic
  end

  def update
    authorize! :update, @topic
    @topic.edited_at = Time.now
    if @topic.update_attributes params[:topic]
      redirect_to topic_path(@topic)
    else
      render :edit
    end
  end

  def destroy
    redirect_to topics_path
  end

  def follow
    @topic.followers.push current_user
    redirect_to topic_path(@topic)
  end

  def unfollow
    @topic.follower_ids.delete current_user.id
    @topic.save
    redirect_to topic_path(@topic)
  end

  def voteup
    @topic.vote!(current_user)
    redirect_to topic_path(@topic)
  end

  def votedown
    @topic.vote!(current_user, -1)
    redirect_to topic_path(@topic)
  end
end

app/helpers/forum/nodes_helper.rb
module Forum::NodesHelper
end

app/helpers/forum/replies_helper.rb
module Forum::RepliesHelper
end

app/helpers/forum/topics_helper.rb
module Forum::TopicsHelper
end

app/views/forum/topics/_aside.html.haml
- topic = aside
#author-profile.widget
  .widget-container
    .avatar= link_to_user_avatar(topic.author, {:size => :large})
    .name
      = link_to_user(topic.author)
      %span.username="(#{topic.author.username})"
    .utility= link_to 'd', 'd'
    .intro= topic.author.intro

app/views/forum/topics/_form.html.haml
= if !form.object.errors.blank?
  = render :partial => 'shared/error_messages', :locals => {:target => form.object}

.field
  .label= form.label :title
  = form.text_field :title, :maxlength => 50
.field
  .label= form.label :content
  = render :partial => 'shared/editor', :object => form, :locals => {:field => :content}
.field
  .label= form.label :tags
  = form.text_field :tag, :class => 'text tags'
  .tips= t '.tags_tips'


= content_for :aside do
  .widget= 'd'

app/views/forum/topics/_list.html.haml
.topics-list.mode-summary
  - list.each_with_index do |topic, index|
    .topic{ :class => "#{cycle('even', 'odd')} #{topic_class(topic)}" }
      .entry-author
        = link_to_user_avatar topic.author
      %h1.entry-title
        = link_to_user topic.author
        = ':'
        = link_to_topic(topic, {:length => 90, :omission => '...'})
      .entry-meta
        = render :partial => 'forum/nodes/list', :object => topic.tag
        - if topic.replies != []
          .last-replied
            = link_to_user topic.replies.last.author
            = t 'time.replied_at', :time => readability_time_format(topic.replied_at)
        = link_to_topic(topic, {:class => 'replies-count'}){|topic| topic.replies.count}

  .paginate= will_paginate list

app/views/forum/topics/_list_icon.html.haml
.topics-list.mode-icon
  - list_icon.each_with_index do |topic, index|
    .topic{:class => "#{index%2 == 0 ? 'even' : 'odd'} #{topic.title.blank? ? 'untitled' : ''}"}
      .entry-author
        = link_to_user_avatar topic.author
      .entry-title
        = link_to_user topic.author
        = ':'
        = topic.title.blank? ? link_to(truncate(sanitize(topic.content.bbcode_to_html({}), :tags => %w()), :length => 90, :omission => '...'), topic_path(topic), :class => 'topic-link') : link_to_topic(topic)
      .entry-utility
        = render :partial => 'forum/nodes/list', :object => topic.tag
        - if topic.replies != []
          .last-replied
            = link_to_user topic.replies.last.author
            = t 'time.replied_at', :time => readability_time_format(topic.replied_at)
        %a.reply-count{:href => topic_path(topic, :anchor => "last#{topic.replies.count}")}
          %span= topic.replies.count
          /= t ".#{topic.type}"

app/views/forum/topics/edit.html.haml
- content_for :title do
  = t('.edit_topic')

- add_breadcrumb t('.edit_topic'), edit_topic_path(@topic)

.widget
  %h1.widget-title= t '.edit_topic'
  .widget-container.topic-form
    = form_for @topic do |form|
      = render :partial => "form", :object => form
      .field= form.submit t('submit.update'), :class => 'button submit'

app/views/forum/topics/new.html.haml
- content_for :title do
  = t('.new_topic')

- add_breadcrumb t('.new_topic'), new_topic_path

.widget
  %h1.widget-title= t '.new_topic'
  .widget-container.topic-form
    = form_for @topic do |form|
      = render :partial => "form", :object => form
      .field= form.submit t('submit.create'), :class => 'button submit'

app/views/forum/topics/show.html.haml
- content_for :title do
  = @topic.format_title(30, '...')

#topic.widget{:class => " #{topic_class(@topic)}"}
  .widget-container
    .head
      %h1.entry-title=@topic.format_title
      .entry-meta
        %span.author= link_to_user(@topic.author)
        %span.date{:title => l(@topic.created_at)}= t 'time.created_at', :time => readability_time_format(@topic.created_at)
        %span.hits= t 'hits', :hits => @topic.hits
        .bookmarks
          %span.sum= @topic.bookmarks
          %span= t '.bookmark'
    - if !@topic[:title].blank?
      .entry-content
        = rich_content(@topic.content)
    .entry-tags
      %span= t('.tags') + ':'
      = render :partial => 'forum/nodes/list', :object => @topic.tag
    .entry-utility
      - if current_user.bookmarks.where(:_id => @topic.id).first != nil
        = link_to t('.unbookmark'), destroy_bookmark_path(topic_path(@topic))
      - else
        = link_to t('.bookmark'), create_bookmark_path(topic_path(@topic))

      - if @topic.follower_ids.include? current_user.id
        = link_to t('.unfollow'), unfollow_topic_path(@topic)
      - else
        = link_to t('.follow'), follow_topic_path(@topic)

      = link_to t('.edit'), edit_topic_path(@topic) if can? :update, @topic
      = link_to t('.delete'), topic_path(@topic), :method => :delete, :confirm => '您真的要删除这个主题吗?' if can? :destroy, @topic

- if @replies.blank?
  #replies-blank.widget
- else
  #replies.widget{:class => ''}
    .widget-container
      .replies-options= ''
      = will_paginate @replies
      = render :partial => 'forum/replies/list', :object => @replies
      = will_paginate @replies

#reply-form.widget
  %h2.widget-title= t '.leave_your_reply'
  .widget-container
    - if logged_in?
      = form_for @topic.replies.new, :url => topic_replies_path(@topic) do |form|
        = render :partial => 'forum/replies/form', :object => form
        .field= form.submit t('submit.submit'), :class => 'button submit'
    - else
      = link_to t '.sign_in', new_session_path





- content_for :aside do
  = render :partial => 'aside', :object => @topic

app/views/forum/topics/tagged.html.haml
.widget.main-list
  %h3.widget-title= 'Topic List'
  .widget-utility
    = link_to t('.new_topic'), new_topic_path
  = render :partial => "list_#{@page_info[:list_mode]}", :object => @topics

- content_for :aside do
  .widget.node-info