config/routes.rb
Manyou::Application.routes.draw do

  root :to => 'home#index'

  get   :latest,   :to => 'home#latest',  :as => :latest_home

  match "/uploads/*path" => "gridfs#serve"

  scope :module => :member do

    get     :login,     :to => 'sessions#new',      :as => :new_session
    post    :login,     :to => 'sessions#create',   :as => :session
    get     :logout,    :to => 'sessions#destroy',  :as => :destroy_session

    resource :account

    resources :users, :only => [:index, :new, :create, :tagged] do
      collection do
        get 'tagged/:key', :action => :tagged, :constraints => { :key => /[^\/]+/ }, :as => :tagged
      end
    end

    resources :users, :path => :user, :except => [:index, :new, :create, :tagged] do
      member do
        get :follow
        get :unfollow
      end
    end

    get 'bookmarks/add*path' => 'bookmarks#create',    :as => :create_bookmark
    get 'bookmarks/del*path' => 'bookmarks#destroy',   :as => :destroy_bookmark

  end

  scope :module => :forum do

    resource :search

    resources :nodes, :only => [:index, :new, :create, :tagged] do
      collection do
        get 'tagged/:key',  :action => :tagged, :constraints => { :key => /[^\/]+/ },   :as => :tagged
      end
    end

    resources :nodes, :path => :node, :except => [:index, :new, :create, :tagged] do
    end

    resources :topics, :only => [:index, :new, :create, :tagged] do
      collection do
        get 'tagged/:key',  :action => :tagged, :constraints => { :key => /[^\/]+/ },   :as => :tagged
      end
    end
    resources :topics, :path => :topic, :except => [:index, :new, :create, :tagged] do
      member do
        get :voteup
        get :votedown
        get :follow
        get :unfollow
      end

      resources :replies do
        member do
          get :voteup
          get :votedown
        end
      end
    end

  end

  namespace :dashboard do
    root :to => 'home#index'

    resources :users, :topics, :tags, :settings
  end

  match '*path', :to => 'errors#routing'

end

app/views/layouts/_flash_messages.html.haml
- if flash[:success]
  .success= flash[:success]

- if flash[:error]
  .error= flash[:error]

- if flash[:notice]
  .notice= flash[:notice]

app/views/layouts/_footer.html.haml
= yield :footer_before
#footer.clearfix
  .wrapper
    = yield :footer_prepend

    #bottom-menu
      %ul
    #copyright
      @ Copyright
      = link_to AppConfig['app_name'], root_path
      = "2011 - #{Time.now.year}"
      |
      Power by
      = link_to 'manyou', 'https://github.com/lolychee/manyou', :target => '_blank'

    = yield :footer_append

= yield :footer_after

app/views/layouts/_header.html.haml
= yield :header_before
#header.clearfix
  .wrapper
    = yield :header_prepend

    #logo= link_to AppConfig[:app_name], root_path
    #site-search
      = render :partial => 'layouts/search', :object => yield(:search)
    #site-nav
      %ul
        %li{:class => "#{page_class == 'home index'  ? 'active' : nil }"}= link_to t('.home'), root_path
        %li{:class => "#{page_class == 'home latest' ? 'active' : nil }"}= link_to t('.latest'), latest_home_path


    #session-menu{:class => "#{logged_in? ? 'logged' : '' }"}
      - if logged_in?
        .current-user= link_to_user(current_user){|user| user_avatar(user, :small) + user.name }
        %ul.user-profile
          /%li= link_to t('.home'), root_path
          /%li= link_to_user current_user
          %li= link_to t('.settings'), edit_account_path
          %li.last= link_to t('.logout'), destroy_session_path
      - else
        %ul
          %li= link_to t('.login'), new_session_path
          %li.last= link_to t('.register'), new_account_path

    = yield :header_append

= yield :header_after

app/views/layouts/_search.html.haml
- form_tag :search, {:method => :get} do
  = text_field_tag :q, search,:id => 'search-query'
  = submit_tag :search, :class => 'button search'

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta{ "charset" => "utf-8" }
    %title= yield :title
    %link{:rel => "shortcut icon", :href => "/favicon.ico"}
    = stylesheet_link_tag 'reset'
    = stylesheet_link_tag 'layout'
    = stylesheet_link_tag 'module'
    = stylesheet_link_tag 'jquery-ui'
    = javascript_include_tag 'jquery.min'
    = javascript_include_tag 'sea', 'data-main' => "application"
    /= javascript_include_tag :defaults
    /= javascript_include_tag "http://www.google.com/jsapi"
    = yield :head
    = csrf_meta_tag

  %body.fixed{ :class => page_class }
    /#header
    = render :partial => 'layouts/header'

    #content.clearfix
      .wrapper
        = yield :content_prepend

        #flash-messages= render :partial => 'layouts/flash_messages'

        #breadcrumbs= render_breadcrumbs({:builder => BreadcrumbsBuilder})

        .container.clearfix{:class => "#{content_for?(:aside)? 'column2' : 'column1'}"}
          .article.clearfix= yield

          - if content_for?(:aside)
            .aside.clearfix= yield :aside

        = yield :content_append


    /#footer
    = render :partial => 'layouts/footer'

    = yield :page_bottom